In [28]:
import pandas as pd
import numpy as np
import json
import ast
from collections import Counter

In [29]:
df_raw = pd.read_csv("../data/kyc_data.csv")
df_result = pd.read_csv("../data/verification_results.csv", index_col="Unnamed: 0")

In [30]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   recordid               8000 non-null   str
 1   datasource             8000 non-null   str
 2   firstinitial           7512 non-null   str
 3   firstname              7530 non-null   str
 4   middlename             7496 non-null   str
 5   lastname               7476 non-null   str
 6   dayofbirth             7366 non-null   str
 7   monthofbirth           7423 non-null   str
 8   yearofbirth            7443 non-null   str
 9   streetname             7511 non-null   str
 10  streetnumber           7499 non-null   str
 11  streettype             7482 non-null   str
 12  city                   7512 non-null   str
 13  region                 7499 non-null   str
 14  postalcode             7524 non-null   str
 15  unitnumber             7499 non-null   str
 16  address1               7468 non-null   str
 17  taxid                  7653 non-null   str
 18  socialinsurancenumber  7678 non-null   str
 19  voterid                7680 non-null   str
 20  gender                 7500 non-null   str
 21  trumatch_confidence    8000 non-null   float64
dtypes: float64(1), str(21)
memory usage: 2.2 MB

In [31]:
df_result.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        1000 non-null   str
 1   verified         1000 non-null   bool
 2   rule_results     1000 non-null   str
 3   rule_assignment  1000 non-null   str
dtypes: bool(1), str(3)
memory usage: 79.7 KB

In [32]:
df_raw.head()

,recordid,datasource,firstinitial,firstname,middlename,lastname,dayofbirth,monthofbirth,yearofbirth,streetname,...,city,region,postalcode,unitnumber,address1,taxid,socialinsurancenumber,voterid,gender,trumatch_confidence
0,record_1,a,match,match,match,NaN,match,match,match,match,...,NaN,match,match,match,NaN,nomatch,nomatch,nomatch,match,0.553762
1,record_1,b,match,match,match,match,match,missing,missing,match,...,match,match,match,match,match,match,nomatch,match,match,0.568361
2,record_1,c,match,match,match,match,match,match,match,match,...,match,nomatch,nomatch,missing,match,match,match,match,missing,0.501050
3,record_1,d,nomatch,match,match,nomatch,match,match,nomatch,match,...,match,nomatch,nomatch,match,nomatch,missing,match,nomatch,nomatch,0.808702
4,record_1,e,match,nomatch,match,match,nomatch,match,nomatch,match,...,match,nomatch,match,match,nomatch,nomatch,match,nomatch,match,0.536946

In [33]:
df_result.head()

,record_id,verified,rule_results,rule_assignment
0,record_1,True,"{""rule_1"":[""a"",""c""],""rule_2"":[""b"",""c""]}","{""rule_1"":""a"",""rule_2"":""b""}"
1,record_10,False,"{""rule_1"":[],""rule_2"":[]}",{}
2,record_100,True,"{""rule_1"":[""a"",""b""],""rule_2"":[""b"",""e""]}","{""rule_1"":""a"",""rule_2"":""b""}"
3,record_1000,False,"{""rule_1"":[],""rule_2"":[]}",{}
4,record_101,True,"{""rule_1"":[""d""],""rule_2"":[""g""]}","{""rule_1"":""d"",""rule_2"":""g""}"

In [37]:
df_verified = df_result[df_result['verified']==True]
df_verified.info()

<class 'pandas.DataFrame'>
Index: 487 entries, 0 to 999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        487 non-null    str
 1   verified         487 non-null    bool
 2   rule_results     487 non-null    str
 3   rule_assignment  487 non-null    str
dtypes: bool(1), str(3)
memory usage: 50.4 KB

In [35]:
counter = Counter()

for val in df_verified["rule_assignment"]:
    d = json.loads(val)
    counter.update(d.values())

print(counter)

Counter({'a': 290, 'b': 273, 'c': 255, 'd': 91, 'e': 26, 'g': 21, 'f': 16, 'h': 2})